apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/project-e68c2595-021c-4ce6-b62/three-tier-repo/frontend:2
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://amanpathakdevops.study/api/tasks"
        ports:
        - containerPort: 3000
